# Generated by Django 5.0.4 on 2024-04-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibliotecaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='ISBN',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='libro',
            name='coleccion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='paginas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='log',
            name='nivel',
            field=models.CharField(choices=[('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('FATAL', 'FATAL')], max_length=20),
        ),
    ]
