# Generated by Django 5.0.4 on 2024-05-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibliotecaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemporcentro',
            name='no_disponible',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemporcentro',
            name='prestado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemporcentro',
            name='reservado',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemcatalogo',
            name='no_disponible',
            field=models.IntegerField(default=0),
        ),
    ]
