# Generated by Django 4.2.11 on 2024-04-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibliotecaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile_photos/default.jpg', upload_to='profile_photos'),
        ),
    ]
