# Generated by Django 5.0.4 on 2024-04-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibliotecaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
