# Generated by Django 5.0.4 on 2024-04-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibliotecaApp', '0003_itemcatalogo_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
