# Generated by Django 5.0.4 on 2024-04-23 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BibliotecaApp', '0004_log_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='usuario',
        ),
    ]
