# Generated by Django 4.2.11 on 2024-04-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibliotecaApp', '0004_alter_libro_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='coleccion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
